server:
  port: 8088

spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/employment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6479
    host: localhost
    password: password
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1